name: render

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  html-render:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: make build
        env:
          VENVDIR: ~/venv

      - name: prepare for publishing
        run: |-
          sed -i '/index.html/d' .gitignore
          rm README.md

      - name: save rendered pages for debugging
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: html-pages
          if-no-files-found: error
          path: |
            **/*.html

      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: pages
